# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('antecedentes', models.TextField()),
                ('enfermedad_actual', models.TextField()),
                ('examen_fisico', models.TextField()),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='ConsultaEmergencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulta por Emergencia',
                'verbose_name_plural': 'Consultas por Emergencia',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('importe', models.FloatField()),
                ('dosis', models.IntegerField()),
                ('periodo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle de Receta',
                'verbose_name_plural': 'Detalles de Receta',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Consulta')),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distrito',
            },
        ),
        migrations.CreateModel(
            name='FuncionesVitales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('presion_arterial', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('talla', models.IntegerField()),
                ('masa_corporal', models.IntegerField()),
                ('diagnostico_mc', models.CharField(choices=[('PesoBajo', 'B'), ('PesoNormal', 'N'), ('Sobrepeso', 'S'), ('Obesidad', 'O'), ('ObesidadSevera', 'OS')], default='N', max_length=15)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Consulta')),
            ],
            options={
                'verbose_name': 'Funciones Vitales',
                'verbose_name_plural': 'Funciones Vitales',
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemoglobina', models.IntegerField()),
                ('endocritos', models.IntegerField()),
                ('globulos_rojos', models.IntegerField()),
                ('globulos_blancos', models.IntegerField()),
                ('tipo_sangre', models.CharField(max_length=10)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Historia')),
            ],
            options={
                'verbose_name': 'Prueba de Laboratorio',
                'verbose_name_plural': 'Pruebas de Laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('dni', models.IntegerField(unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('estado_civil', models.CharField(choices=[('soltero', 'S'), ('casado', 'C'), ('divorciado', 'D'), ('viudo', 'V'), ('conviviente', 'Cn')], max_length=20)),
                ('sexo', models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M')], max_length=20)),
                ('telefono', models.IntegerField()),
                ('ocupacion', models.CharField(choices=[('EstudianteFIA', 'EF'), ('EstudianteFCE', 'ECE'), ('EstudianteSALUD', 'ES'), ('EstudianteFACIHED', 'EED'), ('DocenteFIA', 'DF'), ('DocenteFCE', 'DCE'), ('DocenteSALUD', 'DS'), ('DocenteFACIHED', 'DED'), ('PersonalAdministrativo', 'PAd'), ('EstudianteCAT', 'EC'), ('DocenteCAT', 'DC'), ('Visitas', 'V')], max_length=20)),
                ('direccion_actual', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Distrito')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('precio_compra', models.FloatField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Departamento')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincia',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('recomendacion', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Consulta')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('dni', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M')], max_length=20)),
                ('ocupacion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Periodo'),
        ),
        migrations.AddField(
            model_name='historia',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atencion.Persona'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Provincia'),
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.UnidadMedida'),
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Producto'),
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Tratamiento'),
        ),
        migrations.AddField(
            model_name='consultaemergencia',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Historia'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Historia'),
        ),
    ]
