# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 14:09
from __future__ import unicode_literals

import apps.sad.managers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sad', '0002_auto_20140925_0620'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.sad.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='access',
            name='access_type',
            field=models.CharField(choices=[('INPUT', 'Input'), ('OUTPUT', 'Output')], default='INPUT', max_length=50, verbose_name='Access type'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='module',
            field=models.CharField(choices=[('PRO', 'Profesional'), ('WEB', 'Web informativa'), ('VENTAS', 'Ventas'), ('BACKEND', 'Backend Manager')], default='BACKEND', max_length=50, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='pos',
            field=models.IntegerField(default=1, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AlterField(
            model_name='module',
            name='module',
            field=models.CharField(choices=[('PRO', 'Profesional'), ('WEB', 'Web informativa'), ('VENTAS', 'Ventas'), ('BACKEND', 'Backend Manager')], default='BACKEND', max_length=50, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('ON', 'Activate'), ('OFF', 'Deactivate')], default='ON', max_length=50, verbose_name='Status'),
        ),
    ]
