# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sad', '0003_auto_20160405_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='module',
            field=models.CharField(choices=[('PRO', 'Profesional'), ('WEB', 'Web informativa'), ('VENTAS', 'Ventas'), ('BACKEND', 'Backend Manager'), ('HOTEL', 'Hotel')], default='BACKEND', max_length=50, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module',
            field=models.CharField(choices=[('PRO', 'Profesional'), ('WEB', 'Web informativa'), ('VENTAS', 'Ventas'), ('BACKEND', 'Backend Manager'), ('HOTEL', 'Hotel')], default='BACKEND', max_length=50, verbose_name='Module'),
        ),
    ]
