# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.ImageField(default='associations/default.png', upload_to='associations', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='association',
            name='type_a',
            field=models.CharField(choices=[('GOVERMENT', 'Government'), ('PRIVATE', 'Private'), ('MIXED', 'Mixed'), ('OTHERS', 'Others')], default='PRIVATE', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='logo',
            field=models.ImageField(default='enterprises/default.png', upload_to='enterprises', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='type_e',
            field=models.CharField(choices=[('GOVERMENT', 'Government'), ('PRIVATE', 'Private'), ('MIXED', 'Mixed'), ('OTHERS', 'Others')], default='PRIVATE', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='test_image',
            field=models.ImageField(blank=True, default='test_images/default.png', null=True, upload_to='test_images', verbose_name='Test image'),
        ),
    ]
